[toolchain]
anchor_version = "0.31.1"

[features]
seeds = false
skip-lint = false

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --workspace"

# Add program addresses here as Anchor programs are introduced:
[programs.localnet]
stealth_vault = "3Nz8wUHewqpMuceSLnoeTMyPLaDt9kNzsVMWTCeVMD6M"

[programs.devnet]
stealth_vault = "3Nz8wUHewqpMuceSLnoeTMyPLaDt9kNzsVMWTCeVMD6M"
